name = "camera_control"
description = "camera driver application"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

executables = ["camera_control"]

[[depends-on]]
ada_lib = "*"

[[pins]]
ada_lib  = { path = "../../ada_lib" }

[[depends-on]]
ada_lib_gnoga = "*"

[[pins]]
ada_lib_gnoga  = { path = "../../ada_lib/ada_lib_gnoga" }

[[depends-on]]
camera_lib = "*"

[[pins]]
camera_lib  = { path = "lib" }

[[depends-on]]
video_lib = "*"

[[pins]]
video_lib  = { path = "../lib" }

[[depends-on]]
gnoga = "*"

[[pins]]
gnoga = { path ="/Users/Wayne/GNAT/share" }


