#!/bin/bash
export SUBDIRECTORY=$1
export APPLICATION=$2
export OUTPUT=$3
shift 3

export CURRENT_DIRECTORY=`pwd`
export OUTPUT=$CURRENT_DIRECTORY/$OUTPUT
echo APPLICATION $APPLICATION
echo OUTPUT $OUTPUT
echo rest /$*/

export COMMAND="$SUBDIRECTORY/$APPLICATION $* $VERBOSE"
echo "comand: $COMMAND"  | tee $OUTPUT
$COMMAND 2>&1 | tee -a $OUTPUT

