name = "camera_tests"
description = "aunit tests for camera"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

executables = ["camera_aunit"]

[[depends-on]]
ada_lib_tests = "*"

[[pins]]
ada_lib_tests  = { path = "../../../ada_lib/ada_lib_tests" }

[[depends-on]]
camera_lib_unit_test = "*"

[[pins]]
camera_lib_unit_test  = { path = "../lib/unit_test" }

[[depends-on]]
video_lib = "*"

[[pins]]
video_lib  = { path = "../../lib" }

[[depends-on]]
video_lib_unit_test = "*"

[[pins]]
video_lib_unit_test  = { path = "../../lib/unit_test" }

[[depends-on]]
camera_test_lib = "*"

[[pins]]
camera_test_lib  = { path = "../test_lib" }

[[depends-on]]
ada_lib_gnoga = "*"

[[pins]]
ada_lib_gnoga  = { path = "../../../ada_lib/ada_lib_gnoga" }

[[depends-on]]
gnoga = "*"

[[pins]]
gnoga = { path ="/Users/Wayne/GNAT/share/gpr" }

[[depends-on]]
applications = "*"

[[pins]]
applications  = { path = "../../.." }

[[depends-on]]
gnatcoll = "^23.0.0"
