name = "camera_tests"
description = "aunit tests for camera"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

executables = ["camera_aunit"]

[[depends-on]]
camera_lib_unit_test = "*"

[[pins]]
camera_lib_unit_test  = { path = "../lib/unit_test" }

[[depends-on]]
video_lib = "*"

[[pins]]
video_lib  = { path = "../../lib" }

[[depends-on]]
video_lib_unit_test = "*"

[[pins]]
video_lib_unit_test  = { path = "../../lib/unit_test" }

[[depends-on]]
camera_test_lib = "*"

[[pins]]
camera_test_lib  = { path = "../test_lib" }

[[depends-on]]
gpr = "*"

[[pins]]
gpr  = { path =  "../../../vendor/github.com/gpr" }

[[depends-on]]
gnoga = "*"

[[pins]]
gnoga  = { path = "../../../vendor/github.com/gnoga" }

[[depends-on]]
applications = "*"

[[pins]]
applications  = { path = "../../.." }


[[depends-on]]
gnatcoll = "*"
