name = "test_lib"
description = "camera unit test library"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

[[depends-on]]
camera_lib = "*"

[[pins]]
camera_lib  = { path = "../lib" }

[[depends-on]]
ada_lib = "*"

[[pins]]
ada_lib  = { path = "../../../ada_lib" }

[[depends-on]]
aunit = "*"

[[pins]]
aunit  = { path = "../../../aunit" }



