name = "camera_test_lib"
description = "camera unit test library"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

[[depends-on]]
camera_lib = "*"

[[pins]]
camera_lib  = { path = "../lib" }

[[depends-on]]
ada_lib_gnoga = "*"

[[pins]]
ada_lib_gnoga  = { path = "../../../ada_lib/ada_lib_gnoga" }

[[depends-on]]
ada_lib_tests = "*"

[[pins]]
ada_lib_tests  = { path = "../../../ada_lib/ada_lib_tests" }

[[depends-on]]
aunit = "*"

[[pins]]
aunit  = { path = "../../../aunit" }



