name = "camera_test_lib"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
alr_environment = "~0.1.0-dev"

[[pins]]
alr_environment = { path='../../../..' }

[[depends-on]]
camera_lib = "~0.1.0-dev"

[[pins]]
camera_lib = { path='../lib' }

[[pins]]
gnoga_ada_lib = { path='../../../../gnoga_lib/gnoga_ada_lib' }

[[depends-on]]
ada_lib_test_lib = "~0.1.0-dev"

[[pins]]
ada_lib_test_lib = { path='../../../../ada_lib/ada_lib_test_lib' }
