name = "camera_driver"
description = "run aunit tests for camera"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

executables = ["camera_driver"]

[[depends-on]]
driver_lib = "*"

[[pins]]
driver_lib  = { path = "lib" }

[[depends-on]]
video_lib = "*"

[[pins]]
video_lib  = { path = "../../lib" }

[[depends-on]]
camera_lib = "*"

[[pins]]
camera_lib  = { path = "../lib" }

[[depends-on]]
camera_test_lib = "*"

[[pins]]
camera_test_lib  = { path = "../test_lib" }

[[depends-on]]
gnoga = { path ="/Users/Wayne/GNAT/share/gpr" } = "*"

[[pins]]
gnoga = { path ="/Users/Wayne/GNAT/share/gpr" }  = { path = "../../../gnoga = { path ="/Users/Wayne/GNAT/share/gpr" }" }

[[depends-on]]
aunit = "*"

[[pins]]
aunit  = { path = "../../../aunit" }

[[depends-on]]
applications = "*"

[[pins]]
applications  = { path = "../../.." }



