source ~/.zshrc
export WHICH=$1
export DIRECTORY=`pwd`
echo WHICH $BUILD_MODE BUILD_PROFILE $ADA_APPLICATION_PROFILE ADA_OS_INCLUDE $ADA_OS_INCLUDE

../../../../../global_build.sh $BUILD_MODE $ADA_APPLICATION_PROFILE $DIRECTORY
